<?php
	// Si la page est appelée directement par son adresse, on redirige en passant par la page index
	if (basename($_SERVER["PHP_SELF"]) != "index.php") {
		header("Location:../index.php");
		die("");
	}

	// Pose quelques soucis avec certains serveurs...
	echo "<?xml version=\"1.0\" encoding=\"utf-8\" ?>";
?>


<!DOCTYPE html>
<html lang="fr">

	<!-- **** H E A D **** -->

	<head>	
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Les recettes du chef</title>
		<link rel="stylesheet" type="text/css" href="css/rubriques.css">
		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	</head>

	<!-- **** F I N **** H E A D **** -->



	<!-- **** B O D Y **** -->

	<body>
		<div id="rubriques">
       <h1>Le Duo Dynamique de la Cuisine et de l'Ingénierie !</h1>
       <p>NOTRE ÉQUIPE EST COMPOSÉE DE DEUX PASSIONNÉS DE LA CUISINE QUI ONT DÉCIDÉ DE METTRE LEUR EXPERTISE
CULINAIRE AU SERVICE DU MONDE NUMÉRIQUE. NOUS SOMMES TOUS DEUX ÉTUDIANTS INGÉNIEURS QUI ONT
DÉVELOPPÉ UNE PASSION POUR LA CUISINE, ET NOUS SOMMES RAVIS DE POUVOIR PARTAGER NOS CONNAISSANCES
ET NOTRE EXPÉRIENCE AVEC NOS VISITEURS. DÉCOUVREZ NOTRE HISTOIRE CI-DESSOUS.</p>

        <div>
            <h2>PRÉSENTATION DE L'ÉQUIPE :</h2>
            <p>MARIE DUVAL:
PASSIONNÉE DE CUISINE DEPUIS PETITE, JE SUIS FAN DE PHILIPPE ETCHEBEST. TOUS LES MERCREDI SOIRS,
JE REGARDE TOP CHEF ET CAUCHEMAR EN CUISINE.

MARTIAL HURET:
PASSIONNÉ D'ESCALADE, J'AI BESOIN DE MANGER SAINEMENT. J'AI ALORS DÉVELOPPÉ UNE PASSION POUR
LA CUISINE AFIN DE CONSERVER UNE FOMRE D'ATHLÈTE.</p>
            <h2>NOTRE PASSION POUR LA CUISINE :</h2>
            <p>NOUS AVONS TOUS LES DEUX DÉVELOPPÉ NOTRE PASSION POUR LA CUISINE PENDANT NOTRE
ENFANCE OÙ NOUS AVONS APPRIS À APPRÉCIER LA SCIENCE ET LA PRÉCISION IMPLIQUÉES DANS
L'ART CULINAIRE. NOUS AVONS COMMENCÉ À EXPÉRIMENTER EN CUISINE, À ESSAYER DE
NOUVELLES RECETTES ET À PERFECTIONNER NOS TECHNIQUES.
NOUS AVONS ÉGALEMENT APPRIS À UTILISER LES OUTILS NUMÉRIQUES POUR AMÉLIORER NOTRE
EXPÉRIENCE CULINAIRE, EN EXPLORANT LES RECETTES EN LIGNE ET EN UTILISANT DES
APPLICATIONS POUR TROUVER DES IDÉES DE REPAS EN FONCTION DE NOS GOÛTS ET DE NOS
PRÉFÉRENCES ALIMENTAIRES.</p>
<h2>NOTRE VISION :</h2>
            <p>EN OFFRANT DES OUTILS ET DES RESSOURCES POUR AIDER LES GENS À CUISINER DES PLATS
SAVOUREUX ET CRÉATIFS. NOUS SOMMES CONVAINCUS QUE LA TECHNOLOGIE PEUT AMÉLIORER
L'EXPÉRIENCE CULINAIRE EN AIDANT LES GENS À TROUVER DES RECETTES ADAPTÉES À LEURS
BESOINS, À DÉCOUVRIR DE NOUVELLES TECHNIQUES DE CUISINE ET À AMÉLIORER LEURS
COMPÉTENCES EN MATIÈRE DE CUISINE.

NOUS SOMMES HEUREUX DE POUVOIR COMBINER NOS COMPÉTENCES D'APPRENTIS INGÉNIEURS
AVEC NOTRE PASSION POUR LA CUISINE POUR OFFRIR DES SOLUTIONS INNOVANTES À NOS
VISITEURS.</p>
        </div> </div>

	</body>

	<!-- **** F I N **** B O D Y **** -->

</html>
